// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg3FboLFeuVcsAVWHdCf2mPgmeBplfXFw',
    appId: '1:801979775459:web:45dc5942fbe90080e888d6',
    messagingSenderId: '801979775459',
    projectId: 'bible-53642',
    authDomain: 'bible-53642.firebaseapp.com',
    storageBucket: 'bible-53642.firebasestorage.app',
    measurementId: 'G-M94TJFTMBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4ppUsYvsm1lIbWAol3MXwP3Hdbu2EYac',
    appId: '1:801979775459:android:8b57bd6d57981e41e888d6',
    messagingSenderId: '801979775459',
    projectId: 'bible-53642',
    storageBucket: 'bible-53642.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8Z3h8rIe9tRK1sKHSaCWRlmREDSp0iJ0',
    appId: '1:801979775459:ios:72574809f061b66de888d6',
    messagingSenderId: '801979775459',
    projectId: 'bible-53642',
    storageBucket: 'bible-53642.firebasestorage.app',
    iosBundleId: 'com.lyinkjr.kamusi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8Z3h8rIe9tRK1sKHSaCWRlmREDSp0iJ0',
    appId: '1:801979775459:ios:72574809f061b66de888d6',
    messagingSenderId: '801979775459',
    projectId: 'bible-53642',
    storageBucket: 'bible-53642.firebasestorage.app',
    iosBundleId: 'com.lyinkjr.kamusi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDg3FboLFeuVcsAVWHdCf2mPgmeBplfXFw',
    appId: '1:801979775459:web:6a909ad08799ce7ee888d6',
    messagingSenderId: '801979775459',
    projectId: 'bible-53642',
    authDomain: 'bible-53642.firebaseapp.com',
    storageBucket: 'bible-53642.firebasestorage.app',
    measurementId: 'G-PCXV2F3J6L',
  );
}
